[versions]
minecraft = "26.3"
forge = "26.3-66.0.2"
neoforge = "26.3.0.7-beta"
neoform = "26.3-1"
fabric-loader = "0.19.5"
fabric-api = "0.160.6+26.3"
mixin = "0.17.4+mixin.0.8.7"
forgeconfigapiport = "26.3.1"
wthit-common = "mojmap-20.0.0"
wthit-forge = "mojmap-20.0.0"
wthit-neoforge = "mojmap-20.0.0"
wthit-fabric = "fabric-20.0.0"
jade-common = "8892782" # 26.3.x-26.3.1-neoforge
jade-forge = "8892782" # 26.3.x-26.3.1-neoforge
jade-neoforge = "8892782" # 26.3.x-26.3.1-neoforge
jade-fabric = "8892530" # 26.3.x-26.3.1-fabric
curios = "16.0.0+26.2"
cobblemon-common = "7otgw3aH" # neoforge-1.8.1+1.21.1
cobblemon-neoforge = "7otgw3aH" # neoforge-1.8.1+1.21.1
cobblemon-fabric = "gBW3vLC7" # fabric-1.8.1+1.21.1
iris-common = "1.11.6+26.3-fabric"
iris-fabric = "1.11.6+26.3-fabric"
iris-neoforge = "1.11.6+26.3-fabric"

[libraries]
minecraft-forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
minecraft-neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
minecraft-fabric = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
forgeconfigapiport-common = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi", version.ref = "forgeconfigapiport" }
forgeconfigapiport-fabric = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-fabric", version.ref = "forgeconfigapiport" }
forgeconfigapiport-forge = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-forge", version.ref = "forgeconfigapiport" }
wthit-common = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-common" }
wthit-forge = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-forge" }
wthit-neoforge = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-neoforge" }
wthit-fabric = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-fabric" }
jade-common = { module = "curse.maven:jade-324717", version.ref = "jade-common" }
jade-forge = { module = "curse.maven:jade-324717", version.ref = "jade-forge" }
jade-neoforge = { module = "curse.maven:jade-324717", version.ref = "jade-neoforge" }
jade-fabric = { module = "curse.maven:jade-324717", version.ref = "jade-fabric" }
curios-neoforge = { module = "top.theillusivec4.curios:curios-neoforge", version.ref = "curios" }
eventbus-validator = { module = "net.minecraftforge:eventbus-validator", version = "7.0.6" }
cobblemon-common = { module = "maven.modrinth:cobblemon", version.ref = "cobblemon-common" }
cobblemon-neoforge = { module = "maven.modrinth:cobblemon", version.ref = "cobblemon-neoforge" }
cobblemon-fabric = { module = "maven.modrinth:cobblemon", version.ref = "cobblemon-fabric" }
iris-common = { module = "maven.modrinth:iris", version.ref = "iris-common" }
iris-neoforge = { module = "maven.modrinth:iris", version.ref = "iris-neoforge" }
iris-fabric = { module = "maven.modrinth:iris", version.ref = "iris-fabric" }

[plugins]
modpublishplugin = { id = "me.modmuss50.mod-publish-plugin", version = "2.2.1" }
forgegradle = { id = "net.minecraftforge.gradle", version = "7.0.40" }
fabricloom = { id = "net.fabricmc.fabric-loom", version = "1.17-SNAPSHOT" }
moddevgradle = { id = "net.neoforged.moddev", version = "2.0.147" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.4.1" }
