name: Bug report
description: Create a bug report to help improve Shoulder Surfing
title: "Short description of the bug here"
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Please take following steps seriously before reporting a bug.
        They ensure that your issue can be resolved quickly and reduce overhead for maintainers.
        If your issue is caused by another mod, please open a compatibility issue instead.
      options:
        - label: I have read the text above
          required: true
        - label: The issue occurs when **only** Shoulder Surfing Reloaded and it's required dependencies are installed
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of what the bug is.
        If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Look at '...'
        2. Press '....'
        3. See error
    validations:
      required: true
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft version
      multiple: true
      options:
        - '26.1[.1]'
        - '1.21.11'
        - '1.21.1'
        - '1.20.1'
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Game logs
      description: |
        Navigate to `.minecraft/logs/` and upload the file named `latest.log` to https://mclo.gs/ and paste the link here.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Add any other information about the problem.
    validations:
      required: false
