name: Compatibility issue
description: Report an incompatibility with another mod
title: "Incompatible with MOD NAME HERE"
labels: ["compatibility"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Please take following steps seriously before reporting a compatibility issue.
        They ensure that your issue can be resolved quickly and reduce overhead for maintainers.
        Conflicting mods can be isolated using the method described [here](https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a).
      options:
        - label: I have read the text above
          required: true
        - label: I have read the [compatibility](https://github.com/Exopandora/ShoulderSurfing?tab=readme-ov-file#compatibility) section before submitting a new issue
          required: true
        - label: I have isolated the conflicting mod (using the method described above)
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of how the incompatibility presents itself.
        If applicable, add screenshots to help explain the issue.
    validations:
      required: true
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft version
      multiple: true
      options:
        - '26.1[.1]'
        - '1.21.11'
        - '1.21.1'
        - '1.20.1'
    validations:
      required: true
  - type: input
    id: mod-name
    attributes:
      label: Incompatible mod name
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Incompatible mod version
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Game Logs
      description: |
        Navigate to `.minecraft/logs/` and upload the file named `latest.log` to https://mclo.gs/ and paste the link here.
    validations:
      required: true
